[32m2025-03-13 20:48:50 -0300[0m - dagster - [34mDEBUG[0m - dbt_and_training - a5d3b59a-a4cb-410a-afbe-0763112e241e - 920050 - LOGS_CAPTURED - Started capturing logs in process (pid: 920050).
[32m2025-03-13 20:48:50 -0300[0m - dagster - [34mDEBUG[0m - dbt_and_training - a5d3b59a-a4cb-410a-afbe-0763112e241e - 920050 - model_trained - STEP_START - Started execution of step "model_trained".
[32m2025-03-13 20:48:50 -0300[0m - dagster - [34mDEBUG[0m - dbt_and_training - a5d3b59a-a4cb-410a-afbe-0763112e241e - 920050 - model_trained - LOADED_INPUT - Loaded input "X_train" using input manager "io_manager", from output "X_train" of step "split_data"
[32m2025-03-13 20:48:50 -0300[0m - dagster - [34mDEBUG[0m - dbt_and_training - a5d3b59a-a4cb-410a-afbe-0763112e241e - 920050 - model_trained - LOADED_INPUT - Loaded input "movie2Idx" using input manager "io_manager", from output "movie2Idx" of step "preprocessed_data"
[32m2025-03-13 20:48:51 -0300[0m - dagster - [34mDEBUG[0m - dbt_and_training - a5d3b59a-a4cb-410a-afbe-0763112e241e - 920050 - model_trained - LOADED_INPUT - Loaded input "user2Idx" using input manager "io_manager", from output "user2Idx" of step "preprocessed_data"
[32m2025-03-13 20:48:51 -0300[0m - dagster - [34mDEBUG[0m - dbt_and_training - a5d3b59a-a4cb-410a-afbe-0763112e241e - 920050 - model_trained - LOADED_INPUT - Loaded input "y_train" using input manager "io_manager", from output "y_train" of step "split_data"
[32m2025-03-13 20:48:51 -0300[0m - dagster - [34mDEBUG[0m - dbt_and_training - a5d3b59a-a4cb-410a-afbe-0763112e241e - 920050 - model_trained - STEP_INPUT - Got input "X_train" of type "Any". (Type check passed).
[32m2025-03-13 20:48:51 -0300[0m - dagster - [34mDEBUG[0m - dbt_and_training - a5d3b59a-a4cb-410a-afbe-0763112e241e - 920050 - model_trained - STEP_INPUT - Got input "movie2Idx" of type "Any". (Type check passed).
[32m2025-03-13 20:48:51 -0300[0m - dagster - [34mDEBUG[0m - dbt_and_training - a5d3b59a-a4cb-410a-afbe-0763112e241e - 920050 - model_trained - STEP_INPUT - Got input "user2Idx" of type "Any". (Type check passed).
[32m2025-03-13 20:48:51 -0300[0m - dagster - [34mDEBUG[0m - dbt_and_training - a5d3b59a-a4cb-410a-afbe-0763112e241e - 920050 - model_trained - STEP_INPUT - Got input "y_train" of type "Any". (Type check passed).
[32m2025-03-13 20:48:51 -0300[0m - dagster - [34mERROR[0m - [31mdbt_and_training - a5d3b59a-a4cb-410a-afbe-0763112e241e - 920050 - model_trained - STEP_FAILURE - Execution of step "model_trained" failed.

dagster._core.errors.DagsterUnknownResourceError: Unknown resource `mlflow_resource`. Specify `mlflow_resource` as a required resource on the compute / config function that accessed it.

Stack Trace:
  File "/home/bajiks/.pyenv/versions/3.12.4/envs/mlops-tp-final/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_plan.py", line 245, in dagster_event_sequence_for_step
    yield from check.generator(step_events)
  File "/home/bajiks/.pyenv/versions/3.12.4/envs/mlops-tp-final/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 501, in core_dagster_event_sequence_for_step
    for user_event in _step_output_error_checked_user_event_sequence(
  File "/home/bajiks/.pyenv/versions/3.12.4/envs/mlops-tp-final/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 184, in _step_output_error_checked_user_event_sequence
    for user_event in user_event_sequence:
  File "/home/bajiks/.pyenv/versions/3.12.4/envs/mlops-tp-final/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 88, in _process_asset_results_to_events
    for user_event in user_event_sequence:
  File "/home/bajiks/.pyenv/versions/3.12.4/envs/mlops-tp-final/lib/python3.12/site-packages/dagster/_core/execution/plan/compute.py", line 190, in execute_core_compute
    for step_output in _yield_compute_results(step_context, inputs, compute_fn, compute_context):
  File "/home/bajiks/.pyenv/versions/3.12.4/envs/mlops-tp-final/lib/python3.12/site-packages/dagster/_core/execution/plan/compute.py", line 159, in _yield_compute_results
    for event in iterate_with_context(
  File "/home/bajiks/.pyenv/versions/3.12.4/envs/mlops-tp-final/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 480, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/home/bajiks/.pyenv/versions/3.12.4/envs/mlops-tp-final/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 127, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/home/bajiks/.pyenv/versions/3.12.4/envs/mlops-tp-final/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 115, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bajiks/code/Bajiks/ITBA/final-project/recommender_system/recommender_system/assets/recommender/train_model.py", line 72, in model_trained
    mlflow = context.resources.mlflow_resource
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bajiks/.pyenv/versions/3.12.4/envs/mlops-tp-final/lib/python3.12/site-packages/dagster/_core/definitions/scoped_resources_builder.py", line 30, in __getattr__
    raise DagsterUnknownResourceError(name)
[0m
